# Generated by Django 4.0.6 on 2025-01-01 10:01

from django.db import migrations, models
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_scripttask_unique_code_alter_scripttask_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledScriptTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_path', models.CharField(help_text='Enter the full path of the script to run, e.g., /home/user/scripts/myscript.py', max_length=255, validators=[mysite.models.validate_script_path])),
                ('run_time', models.TimeField(help_text='Time of day to run the script (24-hour format).')),
                ('timezone', models.CharField(default='UTC', help_text='Time zone for the scheduled run, e.g., UTC, Asia/Dubai', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this scheduled task without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was scheduled.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated.')),
            ],
        ),
    ]
