# Generated by Django 4.0.6 on 2025-01-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_scheduledscripttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledscripttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scheduledscripttask',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Toggle to activate/deactivate the task.'),
        ),
        migrations.AlterField(
            model_name='scheduledscripttask',
            name='script_path',
            field=models.CharField(help_text='Enter the full path to the script.', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduledscripttask',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Timezone for the scheduled task.', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledscripttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
