# Generated by Django 4.0.6 on 2025-01-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_scheduledscripttask_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledscripttask',
            name='script_path',
            field=models.CharField(help_text='Enter the full path to the script.', max_length=2550),
        ),
    ]
