# Generated by Django 4.0.6 on 2025-01-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_scheduledscripttask_script_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledscripttask',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='scripttask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('KILLED', 'Killed')], default='PENDING', max_length=10),
        ),
    ]
