# Generated by Django 4.0.6 on 2025-01-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_scheduledscripttask_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_path', models.CharField(help_text='Full path to the script to be executed.', max_length=1024)),
                ('run_time', models.TimeField(help_text='Time to run the task (24-hour format, 00:00 - 23:59).')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to activate or deactivate the task.')),
                ('next_run', models.DateTimeField(blank=True, help_text='The next scheduled run time for this task.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduledScriptTask',
        ),
    ]
