# Generated by Django 4.0.6 on 2025-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_scheduledtask_delete_scheduledscripttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='run_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='script_path',
            field=models.CharField(max_length=1024),
        ),
    ]
