# Generated by Django 4.0.6 on 2026-02-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_scheduledtask_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledScriptTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_path', models.CharField(help_text='Enter the full path to the script.', max_length=2550)),
                ('run_time', models.TimeField(help_text='Time of day to run the script (24-hour format).')),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for the scheduled task.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to activate/deactivate the task.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
        migrations.AlterField(
            model_name='scripttask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('KILLED', 'Killed'), ('STOP_REQUESTED', 'STOP_REQUESTED')], default='PENDING', max_length=32),
        ),
    ]
